### ISSUE TITLE
Cmake error: Cannot find source file: source/basefwd.h

### ISSUE THREAD

**Issue by yoyolicoris** [pongasoft/vst3-again-sample#1]
Hey man~I have tried your again example on Ubuntu 18.04 using Clion 2018.2.4, followed the instructions in your [blog post](https://www.pongasoft.com/blog/yan/vst/2018/03/12/VST-development-notes/), and encountered this error:
```
CMake Error at /home/ycy/VST_SDK/VST3_SDK/base/CMakeLists.txt:70 (add_library):
  Cannot find source file:

    source/basefwd.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at /home/ycy/VST_SDK/VST3_SDK/base/CMakeLists.txt:70 (add_library):
  No SOURCES given to target: base
```

And I cannot find any basefwd.h file under the sdk directory.
I know you only tested it on win & mac, but it seems not like a OS problem.

**Comment by ypujante** [comment]
In the `base/CMakeLists.txt` I can see this:

```
if (VST_SDK)
	add_library(base STATIC ${base_sources})
else()
	add_library(base STATIC ${base_sources} ${base_sources_ext})
endif()
```

the file `basefwd.h` is indeed not present in the folder but is only part of `base_sources_ext` source set. `VST_SDK` should be `TRUE` so that it executes the first `add_library` and not the second one.

I am not sure why  `VST_SDK` is not set to `TRUE` in your case since it is being defined in `cmake/modules/AddVST3Library.cmake` which is itself included by the main `CMakeLists.txt`

**Comment by yoyolicoris** [comment]
Forgot to mention that I'm using vst3 version 3.6.10, not 3.6.9.
I can't find `VST_SDK` in `cmake/modules/AddVST3Library.cmake` either, but after manually remove `base_sources_ext` source set I can build the project successfully. 

Thanks for your kindly help!

**Comment by ypujante** [comment]
I have not tried 3.6.10 yet but glad you were able to build regardless.

**Comment by nickenchev** [comment]
fwiw, I simply put set(VST_SDK ON) in my CMakeLists.txt and it built, I see that the root VST3_SDK CMakeLists.txt sets it directly, which I guess isn't being used directly.

My issue was:

```
CMake Error at /Users/nenchev/Developer/frameworks/VST_SDK/VST3_SDK/public.sdk/CMakeLists.txt:6 (add_library):
  Cannot find source file:

    source/common/pvaluecontainer.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
```

**Comment by hannessolo** [comment]
I'm getting the same error. I have tried both fixes. Now CLion loads the project correctly, but if I try to build "again | debug" it outputs the following error:

    Undefined symbols for architecture x86_64:
      "Steinberg::Vst::BaseWrapper::_setBypass(bool)", referenced from:
          Steinberg::Vst::Vst2Wrapper::setBypass(bool) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::_setEditor(Steinberg::Vst::BaseEditorWrapper*)", referenced from:
          Steinberg::Vst::Vst2Wrapper::init() in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::setupBuses()", referenced from:
          Steinberg::Vst::Vst2Wrapper::setupBuses() in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::_stopProcess()", referenced from:
          Steinberg::Vst::Vst2Wrapper::stopProcess() in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::_setBlockSize(int)", referenced from:
          Steinberg::Vst::Vst2Wrapper::setBlockSize(int) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::_startProcess()", referenced from:
          Steinberg::Vst::Vst2Wrapper::startProcess() in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::setEffectName(char*)", referenced from:
          Steinberg::Vst::Vst2Wrapper::create(Steinberg::IPluginFactory*, char const*, int, long long (*)(AEffect*, int, int, long long, void*, float)) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::setVendorName(char*)", referenced from:
          Steinberg::Vst::Vst2Wrapper::create(Steinberg::IPluginFactory*, char const*, int, long long (*)(AEffect*, int, int, long long, void*, float)) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::_setSampleRate(float)", referenced from:
          Steinberg::Vst::Vst2Wrapper::setSampleRate(float) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::createInstance(char*, char*, void**)", referenced from:
          vtable for Steinberg::Vst::Vst2Wrapper in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::queryInterface(char const*, void**)", referenced from:
          Steinberg::Vst::Vst2Wrapper::queryInterface(char const*, void**) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::setupParameters()", referenced from:
          Steinberg::Vst::Vst2Wrapper::setupParameters() in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::setupProcessing(int)", referenced from:
          Steinberg::Vst::Vst2Wrapper::setProcessPrecision(int) in vst2wrapper.cpp.o
          Steinberg::Vst::Vst2Wrapper::canDo(char*) in vst2wrapper.cpp.o
          Steinberg::Vst::Vst2Wrapper::updateProcessLevel() in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::processMidiEvent(Steinberg::Vst::Event&, char*, bool, int, float, float)", referenced from:
          Steinberg::Vst::Vst2Wrapper::processEvents(VstEvents*) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::restartComponent(int)", referenced from:
          vtable for Steinberg::Vst::Vst2Wrapper in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::setEffectVersion(char*)", referenced from:
          Steinberg::Vst::Vst2Wrapper::create(Steinberg::IPluginFactory*, char const*, int, long long (*)(AEffect*, int, int, long long, void*, float)) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::setSubCategories(char*)", referenced from:
          Steinberg::Vst::Vst2Wrapper::create(Steinberg::IPluginFactory*, char const*, int, long long (*)(AEffect*, int, int, long long, void*, float)) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::_processReplacing(float**, float**, int)", referenced from:
          Steinberg::Vst::Vst2Wrapper::processReplacing(float**, float**, int) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::addParameterChange(unsigned int, double, int)", referenced from:
          Steinberg::Vst::Vst2Wrapper::setParameter(int, float) in vst2wrapper.cpp.o
          Steinberg::Vst::Vst2Wrapper::setProgram(int) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::getLastParamChange(unsigned int, double&)", referenced from:
          Steinberg::Vst::Vst2Wrapper::getParameterDisplay(int, char*) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::notifyUnitSelection(int)", referenced from:
          vtable for Steinberg::Vst::Vst2Wrapper in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::getProgramListAndUnit(int, int&, int&)", referenced from:
          Steinberg::Vst::Vst2Wrapper::getMidiProgramName(int, MidiProgramName*) in vst2wrapper.cpp.o
          Steinberg::Vst::Vst2Wrapper::getCurrentMidiProgram(int, MidiProgramName*) in vst2wrapper.cpp.o
          Steinberg::Vst::Vst2Wrapper::setupProgramCategories() in vst2wrapper.cpp.o
          Steinberg::Vst::Vst2Wrapper::getMidiKeyName(int, MidiKeyName*) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::_processDoubleReplacing(double**, double**, int)", referenced from:
          Steinberg::Vst::Vst2Wrapper::processDoubleReplacing(double**, double**, int) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::notifyProgramListChange(int, int)", referenced from:
          vtable for Steinberg::Vst::Vst2Wrapper in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::getProgramListInfoByProgramListID(int, Steinberg::Vst::ProgramListInfo&)", referenced from:
          Steinberg::Vst::Vst2Wrapper::getMidiProgramName(int, MidiProgramName*) in vst2wrapper.cpp.o
          Steinberg::Vst::Vst2Wrapper::setupProgramCategories() in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::init()", referenced from:
          Steinberg::Vst::Vst2Wrapper::init() in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::_resume()", referenced from:
          Steinberg::Vst::Vst2Wrapper::resume() in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::onTimer(Steinberg::Timer*)", referenced from:
          vtable for Steinberg::Vst::Vst2Wrapper in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::_suspend()", referenced from:
          Steinberg::Vst::Vst2Wrapper::suspend() in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::_getChunk(void**, bool)", referenced from:
          Steinberg::Vst::Vst2Wrapper::getChunk(void**, bool) in vst2wrapper.cpp.o
          vtable for Steinberg::Vst::Vst2Wrapper in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::_setChunk(void*, int, bool)", referenced from:
          Steinberg::Vst::Vst2Wrapper::setChunk(void*, int, bool) in vst2wrapper.cpp.o
          vtable for Steinberg::Vst::Vst2Wrapper in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::BaseWrapper(Steinberg::Vst::BaseWrapper::SVST3Config&)", referenced from:
          Steinberg::Vst::Vst2Wrapper::Vst2Wrapper(Steinberg::Vst::BaseWrapper::SVST3Config&, long long (*)(AEffect*, int, int, long long, void*, float), int) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::~BaseWrapper()", referenced from:
          Steinberg::Vst::Vst2Wrapper::Vst2Wrapper(Steinberg::Vst::BaseWrapper::SVST3Config&, long long (*)(AEffect*, int, int, long long, void*, float), int) in vst2wrapper.cpp.o
          Steinberg::Vst::Vst2Wrapper::~Vst2Wrapper() in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseEditorWrapper::_setKnobMode(int)", referenced from:
          Steinberg::Vst::Vst2EditorWrapper::setKnobMode(int) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseEditorWrapper::queryInterface(char const*, void**)", referenced from:
          vtable for Steinberg::Vst::Vst2EditorWrapper in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseEditorWrapper::_open(void*)", referenced from:
          Steinberg::Vst::Vst2EditorWrapper::open(void*) in vst2wrapper.cpp.o
          vtable for Steinberg::Vst::Vst2EditorWrapper in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseEditorWrapper::_close()", referenced from:
          Steinberg::Vst::Vst2EditorWrapper::_close() in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseEditorWrapper::getRect(Steinberg::ViewRect&)", referenced from:
          Steinberg::Vst::Vst2EditorWrapper::getRect(ERect**) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseEditorWrapper::hasEditor(Steinberg::Vst::IEditController*)", referenced from:
          Steinberg::Vst::Vst2Wrapper::init() in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseEditorWrapper::BaseEditorWrapper(Steinberg::Vst::IEditController*)", referenced from:
          Steinberg::Vst::Vst2EditorWrapper::Vst2EditorWrapper(AudioEffect*, Steinberg::Vst::IEditController*) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseEditorWrapper::~BaseEditorWrapper()", referenced from:
          Steinberg::Vst::Vst2EditorWrapper::~Vst2EditorWrapper() in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::getUnitPath(int, Steinberg::String&) const", referenced from:
          Steinberg::Vst::Vst2Wrapper::getParameterName(int, char*) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::_getParameter(int) const", referenced from:
          Steinberg::Vst::Vst2Wrapper::getParameter(int) in vst2wrapper.cpp.o
      "Steinberg::Vst::BaseWrapper::getEditorSize(int&, int&) const", referenced from:
          vtable for Steinberg::Vst::Vst2Wrapper in vst2wrapper.cpp.o
      "typeinfo for Steinberg::Vst::BaseWrapper", referenced from:
          typeinfo for Steinberg::Vst::Vst2Wrapper in vst2wrapper.cpp.o
      "typeinfo for Steinberg::Vst::BaseEditorWrapper", referenced from:
          typeinfo for Steinberg::Vst::Vst2EditorWrapper in vst2wrapper.cpp.o
      "non-virtual thunk to Steinberg::Vst::BaseWrapper::notifyUnitSelection(int)", referenced from:
          vtable for Steinberg::Vst::Vst2Wrapper in vst2wrapper.cpp.o
      "non-virtual thunk to Steinberg::Vst::BaseWrapper::notifyProgramListChange(int, int)", referenced from:
          vtable for Steinberg::Vst::Vst2Wrapper in vst2wrapper.cpp.o
      "non-virtual thunk to Steinberg::Vst::BaseWrapper::onTimer(Steinberg::Timer*)", referenced from:
          vtable for Steinberg::Vst::Vst2Wrapper in vst2wrapper.cpp.o
      "non-virtual thunk to Steinberg::Vst::BaseWrapper::restartComponent(int)", referenced from:
          vtable for Steinberg::Vst::Vst2Wrapper in vst2wrapper.cpp.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [VST3/Debug/again.vst3/Contents/MacOS/again] Error 1
    make[1]: *** [CMakeFiles/again.dir/all] Error 2
    make: *** [all] Error 2
    
I'm using version 3.6.10. Any help appreciated!

**Comment by ypujante** [comment]
@hannessolo I am not sure what is happening. I created this project a while ago and since then I open sourced another framework/library called [Jamba](https://github.com/pongasoft/jamba) which allows you to create a VST2/3 plugin with one [simple command](https://github.com/pongasoft/jamba#quick-starting-guide) and would suggest you take a look at it as it is way more powerful.

**Comment by hannessolo** [comment]
> @hannessolo I am not sure what is happening. I created this project a while ago and since then I open sourced another framework/library called [Jamba](https://github.com/pongasoft/jamba) which allows you to create a VST2/3 plugin with one [simple command](https://github.com/pongasoft/jamba#quick-starting-guide) and would suggest you take a look at it as it is way more powerful.

Thanks, I'll try that. I really appreciate your guides for setting up VST plugins, they're really needed with the lack of good official documentation.
